version: "3.8"
services: 

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - erp-network
  

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - erp-network
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - erp-network
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - erp-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - erp-network

  mongodb: 
    image: mongo:7
    container_name: mongodb
    restart: always

    ports: 
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: chaima
      MONGO_INITDB_ROOT_PASSWORD: chaima123
      MONGO_INITDB_DATABASE: erp
    networks: 
      - erp-network

  backend: 
    image: chaimahs/backend:latest
    container_name: backend
    restart: always
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    environment: 
      PORT: 5000
      DATABASE_URL: mongodb://chaima:chaima123@mongodb:27017/erp?authSource=admin
    networks: 
      - erp-network

  frontend: 
    image: chaimahs/frontend:latest
    container_name: frontend
    restart: always
    ports: 
      - "3000:80"
    depends_on: 
      - backend
    networks:
      - erp-network
volumes: 
  mongodb_data:
  grafana_data:

networks: 
  erp-network:
    driver: bridge